### ISSUE TITLE
Similarity with https://github.com/rosshemsley/shapecheck

### ISSUE THREAD

**Issue by rosshemsley** [n2cholas/shapecheck#1]
Hey, I noticed more than a passing similarity with my library: https://github.com/rosshemsley/shapecheck

If this was inspired by that, perhaps it would be nice to at least link to it :) ? (unless I am mistaken?)

I may also be interested in collaboration.

**Comment by n2cholas** [comment]
Hi @rosshemsley! I had seen several array checking libraries last year, and chose this name inattentively to avoid clashing with the several arraycheck and tensorcheck libraries. I have given credit to your work (as well as other libraries) in my README.

I did not intend to copy your library or name, and apologize for that. The design of this library is very similar to a few others libraries as well.  If there is anything else I do, please let me know.

I would also be happy to collaborate.

**Comment by rosshemsley** [comment]
:) I was annoyed at myself for being lazy and not pushing it to Pypi, and got a surprise when I went to push it today!

I see you made it work with more generic types, too. I also prototyped that but couldn't come up with a solution I was happy with in the end, so decided to KISS.

I'll take more of a dive at what you came up with later, maybe there's some things worth porting across.

**Comment by n2cholas** [comment]
Thanks, I'm looking forward to hearing those!

It seems like there are some slightly different goals/capabilities between our libraries as well (for example, yours allows naming sub-dimensions like RGB, which I did not consider and seems out of scope).  So, there might be value in both of our packages to co-existing on PyPI, if you expand on those features (which would mean using a new name for mine or yours).

**Comment by rosshemsley** [comment]
The main problems I aimed to solve was "documenting" the dimension conventions. I found I was often encountering code that switched between BGR / RGB / channel-first / channel-last ... (and even batch first / last when using recurrent nets)... and the only way to tell the conventions was to add a print, which can get frustrating.

Some "future feature" ideas I had were to try and tap into the type annotation system, to add checking to the return types and to support more general aggregate types with "natural" syntax, and without incurring performance degradation (e.g. checking a nested array has the correct shape is actually very inefficient)

> which would mean using a new name for mine or yours
Don't worry too much about it, not too precious about this (this is one of those cases that pypi's namespacing kinda sucks, but there ya go)

**Comment by n2cholas** [comment]
Got it, that makes sense. You should check out [tensor_annotations](https://github.com/deepmind/tensor_annotations) as well then, they aim to do some of what you said statically (thanks for bringing this up, this is another library I need to add to my readme haha). 

Outside of Python, you may be interested in the [tensors fitting perfectly](https://github.com/google-research/swift-tfp) package, it also aims to do some checking using compiler features.

**Comment by n2cholas** [comment]
I'll close this since we sorted this out, thanks for bringing it up!
